[package]
name = "TeviVesting"
version = "1.0.0"
authors = []

[addresses]
TeviVesting = "_"
TeviCoin = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dependencies.TeviCoin]
local = "../tevi-coin"

[dev-dependencies]
